# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-01-09 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0002_topic_webpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
